debug: true
pipeline:
  build:
    image: golang:1.8
    environment:
      - HUGO=0.20.7_Linux_64bit
    commands:
      - curl -L -o /tmp/hugo_$HUGO.tar.gz https://github.com/spf13/hugo/releases/download/v0.15/hugo_$HUGO.tar.gz
      - tar xvf /tmp/hugo_$HUGO.tar.gz -C /tmp/
      - mv /tmp/hugo_$HUGO/hugo_$HUGO /usr/bin/hugo
      - hugo -t hugo-uno -b https://kube.camp
