debug: true
pipeline:
  build:
    image: golang:1.8
    environment:
    commands:
      - curl -L -o /tmp/hugo.tar.gz https://github.com/spf13/hugo/releases/download/v0.20.7/hugo_0.20.7_Linux-64bit.tar.gz      
      - tar xvf /tmp/hugo.tar.gz -C /tmp/
      - mv /tmp/hugo /usr/bin/hugo
      - hugo -t beautifulhugo -b https://kube.camp
